// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Planner.Infrastructure.Persistence;

#nullable disable

namespace Planner.Infrastructure.Migrations
{
    [DbContext(typeof(PlannerDbContext))]
    [Migration("20260719192155_AddGoalHierarchy")]
    partial class AddGoalHierarchy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Planner.Domain.Entities.DailyGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WeeklyGoalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyGoalId");

                    b.ToTable("DailyGoals");
                });

            modelBuilder.Entity("Planner.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Planner.Domain.Entities.MonthlyGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("YearlyGoalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("YearlyGoalId");

                    b.ToTable("MonthlyGoals");
                });

            modelBuilder.Entity("Planner.Domain.Entities.WeeklyGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MonthlyGoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyGoalId");

                    b.ToTable("WeeklyGoals");
                });

            modelBuilder.Entity("Planner.Domain.Entities.YearlyGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("YearlyGoals");
                });

            modelBuilder.Entity("Planner.Domain.Entities.DailyGoal", b =>
                {
                    b.HasOne("Planner.Domain.Entities.WeeklyGoal", "WeeklyGoal")
                        .WithMany("DailyGoals")
                        .HasForeignKey("WeeklyGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyGoal");
                });

            modelBuilder.Entity("Planner.Domain.Entities.MonthlyGoal", b =>
                {
                    b.HasOne("Planner.Domain.Entities.YearlyGoal", "YearlyGoal")
                        .WithMany("MonthlyGoals")
                        .HasForeignKey("YearlyGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YearlyGoal");
                });

            modelBuilder.Entity("Planner.Domain.Entities.WeeklyGoal", b =>
                {
                    b.HasOne("Planner.Domain.Entities.MonthlyGoal", "MonthlyGoal")
                        .WithMany("WeeklyGoals")
                        .HasForeignKey("MonthlyGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonthlyGoal");
                });

            modelBuilder.Entity("Planner.Domain.Entities.YearlyGoal", b =>
                {
                    b.HasOne("Planner.Domain.Entities.Goal", "Goal")
                        .WithMany("YearlyGoals")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("Planner.Domain.Entities.Goal", b =>
                {
                    b.Navigation("YearlyGoals");
                });

            modelBuilder.Entity("Planner.Domain.Entities.MonthlyGoal", b =>
                {
                    b.Navigation("WeeklyGoals");
                });

            modelBuilder.Entity("Planner.Domain.Entities.WeeklyGoal", b =>
                {
                    b.Navigation("DailyGoals");
                });

            modelBuilder.Entity("Planner.Domain.Entities.YearlyGoal", b =>
                {
                    b.Navigation("MonthlyGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
